# Site configuration
domain: "https://lingyes.xyz/"
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://ling-y.github.io/" # the base hostname & protocol for your site
permalink: /:title/
# avatar: /murmur/assets/avatar.jpg
# about: /murmur/assets/about.jpg
# favicon: /murmur/assets/favicon.ico
basecss: 
# Theme specific configuration
title: LING
description: > 

# Contact and social media links
# twitter_username: songrogero
# github_username: songroger
# facebook_username: song.roger.1
# instagram_username: songroger198
# linkedin_username: songroger

exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account
# before deploy your webpage
enable_comment: false
# disqus_account: songroger


 #Google Analytics
ga_track_id: 'UA-149664959-1'            # Format: UA-xxxxxx-xx
ga_domain: https://lingyea.xyz


# gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: archive/page:num

plugins:
    - jekyll-paginate
